version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket contentdiscovery.quickstart.package --output-template-file quickstart-output.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - quickstart-output.yaml